- name: 'deploy to aws'
  hosts: all
  become: yes
  remote_user: ec2-user

  tasks:
    - name: Install and enable required packages
      include: ../packages/packages.yaml

    - name: Copy docker-compose
      copy:
        src: docker-compose.yaml
        dest: /home/ec2-user/test-balance/docker-compose.yaml

    - name: Stop docker-compose
      shell: >
        /usr/local/bin/docker-compose -f "/home/ec2-user/test-balance/docker-compose.yaml" down
      become: yes

    - name: Pull docker images
      shell: >
        /usr/local/bin/docker-compose -f "/home/ec2-user/test-balance/docker-compose.yaml" pull
      become: yes

    - name: Run docker-compose
      shell: >
        /usr/local/bin/docker-compose -f "/home/ec2-user/test-balance/docker-compose.yaml" up -d
      become: yes
      environment:
        KAFKA_BROKERS: "{{ lookup('env','KAFKA_BROKERS') }}"
        KAFKA_SASL_USERNAME: "{{ lookup('env','KAFKA_SASL_USERNAME') }}"
        KAFKA_SASL_PASSWORD: "{{ lookup('env','KAFKA_SASL_PASSWORD') }}"
        DB_NAME: "{{ lookup('env','DB_NAME') }}"
        DB_USER: "{{ lookup('env','DB_USER') }}"
        DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
        KAFKA_CLIENT_ID_TESTNET: "{{ lookup('env','KAFKA_CLIENT_ID_TESTNET') }}"
        KAFKA_CLIENT_ID_WRSH: "{{ lookup('env','KAFKA_CLIENT_ID_WRSH') }}"
        KAFKA_GROUP_ID_TESTNET: "{{ lookup('env','KAFKA_GROUP_ID_TESTNET') }}"
        KAFKA_GROUP_ID_WRSH: "{{ lookup('env','KAFKA_GROUP_ID_WRSH') }}"
        WS_PROVIDER_TESTNET: "{{ lookup('env','WS_PROVIDER_TESTNET') }}"
        WS_PROVIDER_WRSH: "{{ lookup('env','WS_PROVIDER_WRSH') }}"
        ROOT_ACCOUNT_SEED_TESTNET: "{{ lookup('env','ROOT_ACCOUNT_SEED_TESTNET') }}"
        ROOT_ACCOUNT_SEED_WRSH: "{{ lookup('env','ROOT_ACCOUNT_SEED_WRSH') }}"
        TEST_ACCOUNT_SEED: "{{ lookup('env','TEST_ACCOUNT_SEED') }}"
        TEST_ACCOUNT_BALANCE_TESTNET: "{{ lookup('env','TEST_ACCOUNT_BALANCE_TESTNET') }}"
        TEST_ACCOUNT_BALANCE_WRSH: "{{ lookup('env','TEST_ACCOUNT_BALANCE_WRSH') }}"
        TEST_BALANCE_VALUE_TESTNET: "{{ lookup('env','TEST_BALANCE_VALUE_TESTNET') }}"
        TEST_BALANCE_VALUE_WRSH: "{{ lookup('env','TEST_BALANCE_VALUE_WRSH') }}"

    - name: Install nginx with self-signed certs
      include: ../nginx/nginx.yaml
