{
 "title": "Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "node_exporter",
    "label": "Check resources on",
    "query": {
     "query": "label_values({job=\"node_exporter\"},instance)"
    }
   },
   {
    "name": "substrate_exporter",
    "label": "Check blocks production on",
    "query": {
     "query": "label_values({job=\"substrate_exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Blockchain Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count finalized blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{instance=~\"$substrate_exporter\",status=~\"finalized\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blocks rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_block_height{instance=~\"$substrate_exporter\",status=\"finalized\"}[1m])*60",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{instance=~\"$substrate_exporter\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Resource Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System Load (15 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$node_exporter\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node_exporter\",mode=\"idle\"}[60s])) by (hostname))*100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node_exporter\"} - node_memory_MemAvailable_bytes{instance=~\"$node_exporter\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node_exporter',fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{instance=~'$node_exporter',fstype=~\"ext.*|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~'$node_exporter',fstype=~\"ext.*|xfs\"}+(node_filesystem_size_bytes{instance=~'$node_exporter',fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{instance=~'$node_exporter',fstype=~\"ext.*|xfs\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node_exporter\"}[1m])",
     "legendFormat": "{{hostname}} Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node_exporter\"}[1m])",
     "legendFormat": "{{hostname}} Write"
    }
   ]
  },
  {
   "title": "Network bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$node_exporter\",device=\"eth0\"}[1m])*8",
     "legendFormat": "{{hostname}} Input"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node_exporter\",device=\"eth0\"}[1m])*8",
     "legendFormat": "{{hostname}} Output"
    }
   ]
  },
  {
   "title": "AWS EFS Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_efs_storage_bytes_maximum{storage_class=\"Total\"}",
     "legendFormat": "{{file_system_id}}"
    }
   ]
  }
 ]
}