openapi: 3.0.0
info:
  title: API documentation
  version: 1.1.0
components:
  schemas:
    VaraTestnetRequest:
      type: object
      properties:
        token:
          type: string
          description: hCaptcha token
        payload:
          type: object
          description: Balance payload
          properties:
            address:
              type: string
              description: Public wallet address
            genesis:
              type: string
              description: Genesis block hash
      required:
        - token
        - payload
    VaraBridgeRequest:
      type: object
      properties:
        token:
          type: string
          description: hCaptcha token
        address:
          type: string
          description: Account address
        contract:
          type: string
          description: Address of the ERC20 contract
      required:
        - token
        - address
        - contract

paths:
  /balance:
    post:
      summary: Request test balance on Vara Testnet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VaraTestnetRequest'
            example:
              payload:
                address: 'account address'
                genesis: 'network genesis'
              token: 'hCaptcha token'
      responses:
        '200':
          description: Request submitted succesfully
        '400':
          description: Bad request, missing or invalid parameters
          content:
            application/json:
              examples:
                MissingParameters: { error: 'Address and genesis are required' }
                InvalidAddress: { error: 'Invalid account address' }
                UnsupportedNetwork: { error: '0x<genesis> is not supported' }

        '403':
          description: Forbidden, transfer limit reached
          content:
            application/json:
              example: { error: 'The limit for requesting test balance has been reached.' }
        '500':
          description: A server internal error
          content:
            application/json:
              example: { error: 'InternalError' }
  /bridge/request:
    post:
      summary: Request test tokens on ERC20 contracts used by Vara bridge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VaraBridgeRequest'
            example:
              address: '0x<public_key>'
              contract: '0x<erc20_address>'
              token: 'hCaptcha token'
      responses:
        '200':
          description: Request submitted succesfully
        '400':
          description: Bad request, missing or invalid parameters
          content:
            application/json:
              examples:
                MissingParameters: { error: 'Address and genesis are required' }
                InvalidAddress: { error: 'Invalid account address' }
                UnsupportedContract: { error: '0x<contract_address> is not supported' }

        '403':
          description: Forbidden, transfer limit reached
          content:
            application/json:
              example: { error: 'The limit for requesting test balance has been reached.' }
        '500':
          description: A server internal error
          content:
            application/json:
              example: { error: 'InternalError' }
