---
#Install/update backend docker-compose
- name: Create kafka dir
  file: path=/home/ec2-user/kafka state=kafka mode=0755
  
- name: Copy docker-compose
  copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/kafka/docker-compose.yaml

- name: Stop docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/kafka/docker-compose.yaml" down
  become: yes

- name: Pull docker images
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/kafka/docker-compose.yaml" pull
  become: yes

- name: Remove old docker images
  shell: docker image prune -f
  become: yes

- name: Run docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/kafka/docker-compose.yaml" up -d
  become: yes
