import {
  DEFAULT_ERROR_OPTIONS,
  DEFAULT_INFO_OPTIONS,
  DEFAULT_LOADING_OPTIONS,
  DEFAULT_OPTIONS,
  DEFAULT_SUCCESS_OPTIONS,
} from './alert';

const VARA_SS58_FORMAT = 137;

export {
  DEFAULT_ERROR_OPTIONS,
  DEFAULT_INFO_OPTIONS,
  DEFAULT_LOADING_OPTIONS,
  DEFAULT_OPTIONS,
  DEFAULT_SUCCESS_OPTIONS,
  VARA_SS58_FORMAT,
};
