import {
  DEFAULT_OPTIONS,
  DEFAULT_INFO_OPTIONS,
  DEFAULT_ERROR_OPTIONS,
  DEFAULT_SUCCESS_OPTIONS,
  DEFAULT_LOADING_OPTIONS,
} from './alert';

const LOCAL_STORAGE = {
  ACCOUNT: 'account',
};

const VARA_SS58_FORMAT = 137;

export {
  DEFAULT_OPTIONS,
  DEFAULT_INFO_OPTIONS,
  DEFAULT_ERROR_OPTIONS,
  DEFAULT_SUCCESS_OPTIONS,
  DEFAULT_LOADING_OPTIONS,
  LOCAL_STORAGE,
  VARA_SS58_FORMAT,
};
