kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: api-gateway-testenv
  labels:
    app: api-gateway-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-testenv
  template:
    metadata:
      labels:
        app: api-gateway-testenv
    spec:
      containers:
        - name: api-gateway-test
          image: ghcr.io/gear-tech/gear-js-api-gateway:dev
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_GROUP_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_BROKERS
              value: kafka-testenv:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: password
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-testenv
  namespace: test-env
  labels:
    app: api-gateway-testenv
spec:
  ports:
  - port: 3000
    name: api-gateway-testenv
  selector:
    app: api-gateway-testenv
