version: 2
updates:
  - package-ecosystem: 'github-actions'
    labels:
      - D4-dependencies
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/GMT
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    labels:
      - D4-dependencies
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/GMT
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    groups:
      development:
        dependency-type: 'development'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
        update-types:
          - "minor"
          - "patch"
      production-patch:
        dependency-type: 'production'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
        update-types:
          - "patch"
      production-minor:
        dependency-type: 'production'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
        update-types:
          - "minor"
      production-major:
        dependency-type: 'production'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
        update-types:
          - "major"
      polkadot:
        patterns:
          - '@polkadot/*'
      sails:
        patterns:
          - 'sails-js*'
      major-updates:
        update-types:
          - "major"
