version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'

  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: weekly
    versioning-strategy: 'increase'
