version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/api'
    labels:
      - dependency
      - api
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'osipov-mit'

  - package-ecosystem: 'npm'
    directory: '/utils/meta-cli'
    labels:
      - dependency
      - gear-meta
    schedule:
      interval: 'weekly'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'osipov-mit'

  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - dependency
      - website
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'osipov-mit'
      - 'aderrod94'
      - 'codev0'
      - 'nikitayutanov'
