version: 2
updates:
  - package-ecosystem: 'github-actions'
    labels:
      - D4-dependencies
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    labels:
      - D4-dependencies
    schedule:
      interval: daily
    groups:
      development:
        dependency-type: 'development'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
      production:
        dependency-type: 'production'
        exclude-patterns:
          - '@polkadot/*'
          - 'sails-js*'
      polkadot:
        patterns:
          - '@polkadot/*'
      sails:
        patterns:
          - 'sails-js*'
