version: 2
updates:
  - package-ecosystem: 'npm'
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(repo):'
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/apis/gear'
    open-pull-requests-limit: 1
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(api):'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'

  - package-ecosystem: 'npm'
    directories:
      - '/idea/gear/*'
    open-pull-requests-limit: 1
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(gear-idea):'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'

  - package-ecosystem: 'npm'
    directories:
      - '/utils/*'
    open-pull-requests-limit: 1
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(utils):'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'

  - package-ecosystem: 'npm'
    directories:
      - '/tools/*'
    open-pull-requests-limit: 1
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(tools):'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
