kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev-1
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-cluster:9094
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zookeeper:2181

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: dev-1
  labels:
    app: kafka-ui
spec:
  ports:
  - port: 8080
    nodePort: 31100
    name: kafka-ui
  selector:
    app: kafka-ui
  type: NodePort
