kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev-1
  name: data-storage
  labels:
    app: data-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers:
        - name: data-storage
          image: mithriy/gear-data-storage:nightly
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: password
            - name: DB_HOST
              value: postgres
            - name: KAFKA_CLIENT_ID
              value: gear-data-storage
            - name: KAFKA_GROUP_ID
              value: gear-main
            - name: KAFKA_BROKERS
              value: kafka-cluster:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: password
          imagePullPolicy: Always

