version: '3'

services:
  backend:
    depends_on:
      - kafka
    restart: always
    ports:
      - 3000:3000
    image: mithriy/gear-api-gateway:nightly
    environment:
      CLIENT_ID: ${API_BACKEND_KAFKA_CLIENT_ID}
      GROUP_ID: ${API_BACKEND_KAFKA_GROUP_ID}
      BROKERS: kafka:9092
      PORT: 3000

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /home/ec2/db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  data-storage:
    image: mithriy/gear-data-storage:nightly
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - CLIENT_ID=${DATA_STORAGE_KAFKA_CLIENT_ID}
      - GROUP_ID=${DATA_STORAGE_KAFKA_GROUP_ID}
      - KAFKA_BROKERS=kafka:9092
