kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev-1
  name: events-listener-rpc-testnet
  labels:
    app: events-listener-rpc-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-listener-rpc-testnet
  template:
    metadata:
      labels:
        app: events-listener-rpc-testnet
    spec:
      containers:
        - name: events-listener-rpc-testnet
          image: ghcr.io/gear-tech/gear-js-events-listener:dev
          env:
            - name: KAFKA_CLIENT_ID
              value: events-rpc-testnet
            - name: KAFKA_BROKERS
              value: kafka-cluster:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: password
            - name: WS_PROVIDER
              value: wss://rpc-node.gear-tech.io:443
          imagePullPolicy: Always


