kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: frontend-nginx-testenv
  labels:
    app: frontend-nginx-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx-testenv
  template:
    metadata:
      labels:
        app: frontend-nginx-testenv
    spec:
      containers:
        - name: frontend-nginx-testenv
          image: ghcr.io/gear-tech/gear-js-frontend:dev
          volumeMounts:
            - name: nginx-gear-frontend-testenv
              readOnly: true
              mountPath: /etc/nginx/conf.d/
            - name: gear-nodes-testenv
              readOnly: true
              mountPath: /opt/gear-nodes/
            - name: nginx-conf-testenv
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_URL
              value: https://test-env.gear-tech.io/api
            - name: REACT_APP_NODE_ADDRESS
              value: wss://test-env.gear-tech.io/gear-testnet
            - name: REACT_APP_WASM_COMPILER_URL
              value: https://idea.gear-tech.io/wasm-compiler
            - name: REACT_APP_DEFAULT_NODES_URL
              value: https://test-env.gear-tech.io/gear-nodes
      volumes:
        - name: nginx-gear-frontend-testenv
          configMap:
            name: nginx-gear-frontend-testenv
            defaultMode: 420
        - name: gear-nodes-testenv
          configMap:
            name: gear-nodes-testenv
            defaultMode: 420
        - name: nginx-conf-testenv
          configMap:
            name: nginx-conf-testenv
            defaultMode: 420 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-testenv
  namespace: test-env
  labels:
    app: frontend-nginx-testenv
spec:
  ports:
    - port: 80
      name: frontend-nginx-testenv
  selector:
    app: frontend-nginx-testenv
