[profile.default]
src = "contracts"
out = "out"
libs = [
    "node_modules",
    "solidity_lib"
]
remappings = ["forge-std/=solidity_lib/forge-std/src/"]
optimizer = true
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
