export const routes = {
  main: '/',
  uploadProgram: '/upload-program',
  uploadedPrograms: '/uploaded-programs',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  editor: '/editor',
  allPrograms: '/all-programs',
  program: '/program/:programId',
  messages: '/messages',
  message: '/message/:messageId',
  state: '/state/:programId',
  send: '/send',
  sendMessage: 'message/:programId',
  reply: 'reply/:messageId',
  meta: '/meta/:programId',
  mailbox: '/mailbox',
  explorer: '/explorer',
};
