export const routes = {
  main: '/',
  uploadProgram: '/upload-program',
  uploadedPrograms: '/uploaded-programs',
  privacyPolicy: '/privacy-policy',
  termsOfUse: '/terms-of-use',
  editor: '/editor',
  allPrograms: '/all-programs',
  notifications: '/notifications',
  program: '/program/:id',
  messages: '/messages',
  message: '/message/:id',
  state: '/state/:id',
  sendMessage: '/send-message/:id',
  replyMessage: '/reply-message/:id',
  mailbox: '/mailbox',
  explorer: '/explorer/:blockId?',
};
