type ActorId = struct {
  [u8, 32],
};

type Role = enum {
  Admin,
  Burner,
  Minter,
};

constructor {
  New : (name: str, symbol: str, decimals: u8);
};

service Admin {
  AllowancesReserve : (additional: u32) -> null;
  BalancesReserve : (additional: u32) -> null;
  BatchMint : (to: vec ActorId, values: vec u256) -> bool;
  Burn : (from: actor_id, value: u256) -> bool;
  GrantRole : (to: actor_id, role: Role) -> bool;
  Kill : (inheritor: actor_id) -> null;
  Mint : (to: actor_id, value: u256) -> bool;
  RemoveRole : (from: actor_id, role: Role) -> bool;
  query Allowances : (skip: u32, take: u32) -> vec struct { struct { actor_id, actor_id }, u256 };
  query Balances : (skip: u32, take: u32) -> vec struct { actor_id, u256 };
  query HasRole : (actor: actor_id, role: str) -> bool;
  query MapsData : () -> struct { struct { u32, u32 }, struct { u32, u32 } };
  query Roles : () -> vec str;

  events {
    Minted: struct { to: actor_id, value: u256 };
    Burned: struct { from: actor_id, value: u256 };
    Killed: struct { inheritor: actor_id };
    BatchMinted: struct { to: vec ActorId, values: vec u256 };
  }
};

service Erc20 {
  Approve : (spender: actor_id, value: u256) -> bool;
  Transfer : (to: actor_id, value: u256) -> bool;
  TransferFrom : (from: actor_id, to: actor_id, value: u256) -> bool;
  query Allowance : (owner: actor_id, spender: actor_id) -> u256;
  query BalanceOf : (owner: actor_id) -> u256;
  query Decimals : () -> u8;
  query Name : () -> str;
  query Symbol : () -> str;
  query TotalSupply : () -> u256;

  events {
    Approval: struct { owner: actor_id, spender: actor_id, value: u256 };
    Transfer: struct { from: actor_id, to: actor_id, value: u256 };
  }
};

service Pausable {
  DelegateAdmin : (actor: actor_id) -> bool;
  Pause : () -> bool;
  Unpause : () -> bool;
  query IsPaused : () -> bool;

  events {
    Paused;
    Unpaused;
  }
};
