---
#Install/update backend docker-compose
- name: Create api-backend dir
  file: path=/home/ec2-user/api-backend state=directory mode=0755
  
- name: Copy docker-compose
  copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/api-backend/docker-compose.yaml

- name: Stop docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/api-backend/docker-compose.yaml" down
  become: yes

- name: Pull docker images
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/api-backend/docker-compose.yaml" pull
  become: yes

- name: Remove old docker images
  shell: docker image prune -f
  become: yes

- name: Run docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/api-backend/docker-compose.yaml" up -d
  become: yes
  environment:
    KAFKA_API_BACKEND_CLIENT_ID: "{{ lookup('env','KAFKA_API_BACKEND_CLIENT_ID') }}"
    KAFKA_API_BACKEND_GROUP_ID: "{{ lookup('env','KAFKA_API_BACKEND_GROUP_ID') }}"
    KAFKA_BROKERS: "{{ lookup('env','KAFKA_BROKERS') }}"
    API_BACKEND_PORT: "{{ lookup('env','API_BACKEND_PORT') }}"
