version: '3'
services:
  backend:
    ports:
      - '3001:3001'
    image: mithriy/gear-api-backend:nightly
    environment:
      - CLIENT_ID=${KAFKA_API_BACKEND_CLIENT_ID}
      - GROUP_ID=${KAFKA_API_BACKEND_GROUP_ID}
      - BROKERS=${KAFKA_BROKERS}
      - PORT=${API_BACKEND_PORT}
