version: '3'
services:
  events:
    restart: always
    image: mithriy/gear-event-listener:nightly
    environment:
      - CLIENT_ID=${EVENT_LISTENER_KAFKA_CLIENT_ID}
      - BROKERS=${KAFKA_BROKERS}
      - WS_PROVIDER=${EVENT_LISTENER_WS_PROVIDER}
