---
#Install/update backend docker-compose
- name: Copy docker-compose
  copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/data-storage/docker-compose.yaml

- name: Stop docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/data-storage/docker-compose.yaml" down
  become: yes

- name: Pull docker images
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/data-storage/docker-compose.yaml" pull
  become: yes

- name: Remove old docker images
  shell: docker image prune -f
  become: yes

- name: Run docker-compose
  shell: >
    /usr/local/bin/docker-compose -f "/home/ec2-user/data-storage/docker-compose.yaml" up -d
  become: yes
  environment:
    DB_NAME: "{{ lookup('env','DB_NAME') }}"
    DB_USER: "{{ lookup('env','DB_USER') }}"
    DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
    DB_PORT: "{{ lookup('env','DB_PORT') }}"
    DB_HOST: "{{ lookup('env','DB_HOST') }}"
    KAFKA_DATA_STORAGE_CLIENT_ID: "{{ lookup('env','KAFKA_DATA_STORAGE_CLIENT_ID') }}"
    KAFKA_DATA_STORAGE_GROUP_ID: "{{ lookup('env','KAFKA_DATA_STORAGE_GROUP_ID') }}"
    KAFKA_BROKERS: "{{ lookup('env','KAFKA_BROKERS') }}"
