kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: test-balance-testenv
  labels:
    app: test-balance-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-balance-testenv
  template:
    metadata:
      labels:
        app: test-balance-testenv
    spec:
      containers:
        - name: test-balance-testenv
          image: ghcr.io/gear-tech/gear-js-test-balance:dev
          env:
            - name: DB_HOST
              value: postgres-testbalance-testenv
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-testenv-secrets
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-testenv-secrets
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-testenv-secrets
                  key: password
            - name: KAFKA_CLIENT_ID
              value: test-balance-workshop
            - name: KAFKA_GROUP_ID
              value: gear-workshop
            - name: KAFKA_BROKERS
              value: kafka-testenv:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: password
            - name: WS_PROVIDER
              value: ws://gear-node:9944
            - name: ROOT_ACCOUNT_SEED
              value: //Alice
            - name: TEST_ACCOUNT_SEED
              value: 0x8999331c53e3a76e31d91767d0e2a91529e96e0e008089a0d34e1919c0d84da5
            - name: TEST_ACCOUNT_BALANCE
              value: "9000000000000"
            - name: TEST_BALANCE_VALUE
              value: "19999999999"
          imagePullPolicy: Always
