kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: events-listener-rpc-testenv
  labels:
    app: events-listener-rpc-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-listener-rpc-testenv
  template:
    metadata:
      labels:
        app: events-listener-rpc-testenv
    spec:
      containers:
        - name: events-listener-rpc-testenv
          image: ghcr.io/gear-tech/gear-js-events-listener:dev
          env:
            - name: KAFKA_CLIENT_ID
              value: events-rpc-testnet
            - name: KAFKA_BROKERS
              value: kafka-testenv:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: password
            - name: WS_PROVIDER
              value: ws://gear-node:9944
          imagePullPolicy: Always
