kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev-1
  name: test-balance-workshop-node
  labels:
    app: test-balance-workshop-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-balance-workshop-node
  template:
    metadata:
      labels:
        app: test-balance-workshop-node
    spec:
      containers:
        - name: test-balance-workshop-node
          image: ghcr.io/gear-tech/gear-js-test-balance:dev
          env:
            - name: DB_HOST
              value: postgres-testbalance
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-secrets
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-secrets
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-testbalance-secrets
                  key: password
            - name: KAFKA_CLIENT_ID
              value: test-balance-workshop
            - name: KAFKA_GROUP_ID
              value: gear-workshop
            - name: KAFKA_BROKERS
              value: kafka-cluster:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: password
            - name: WS_PROVIDER
              value: wss://node-workshop.gear.rs:443
            - name: ROOT_ACCOUNT_SEED
              value: //Alice
            - name: TEST_ACCOUNT_SEED
              value: put here value
            - name: TEST_ACCOUNT_BALANCE
              value: "9000000000000"
            - name: TEST_BALANCE_VALUE
              value: "19999999999"
          imagePullPolicy: Always
