kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: data-storage-testenv
  labels:
    app: data-storage-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storage-testenv
  template:
    metadata:
      labels:
        app: data-storage-testenv
    spec:
      containers:
        - name: data-storage-testenv
          image: ghcr.io/gear-tech/gear-js-data-storage:dev
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-testenv
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-testenv
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-testenv
                  key: password
            - name: DB_HOST
              value: postgres-testenv
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_GROUP_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_BROKERS
              value: kafka-testenv:9094
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-testenv-secrets
                  key: password
          imagePullPolicy: Always

