FROM ghcr.io/gear-tech/node-vara:latest
MAINTAINER GEAR
CMD ["gear-node",  "--chain vara-dev", "--validator", "--tmp", "--unsafe-ws-external", "--unsafe-rpc-external", "--rpc-methods", "Unsafe", "--rpc-cors", "all"]
