- name: 'deploy frontend'
  hosts: all
  become: yes
  remote_user: ec2-user

  #Set env vars on remote from envs on runner
  environment:
    REACT_APP_GITHUB_CLIENT_ID: "{{ lookup('env','GITHUB_CLIENT_ID') }}"
    REACT_APP_GITHUB_CALLBACK_URL: "https://{{ lookup('env','NODE_ADDRESS') }}/callback"
    REACT_APP_TELEGRAM_BOT_NAME: "{{ lookup('env','TELEGRAM_BOT_USERNAME') }}"
    REACT_APP_API_PATH: "https://{{ lookup('env','NODE_ADDRESS') }}/api"
    REACT_APP_WS_URI: "wss://{{ lookup('env','NODE_ADDRESS') }}/api/ws"
    REACT_APP_IDE_URI: "https://{{ lookup('env','NODE_ADDRESS') }}/ide"
    REACT_APP_RRT: "{{ lookup('env','REACT_APP_RRT') }}"
    REACT_APP_API_CONNECT_ADDRESS: "{{ lookup('env','WS_PROVIDER') }}"

  #Do tasks
  tasks:
    - name: Install and enable required packages
      include: tasks/packages/packages.yaml

    - name: Install frontend
      include: tasks/frontend/frontend.yaml

    - name: Install nginx with self-signed certs
      include: tasks/nginx/nginx.yaml
