- name: 'deploy to aws'
  hosts: all
  become: yes
  remote_user: ec2-user

  #Set env vars on remote from envs on runner
  environment:
    PORT: "{{ lookup('env','PORT') }}"
    DB_NAME: "{{ lookup('env','DB_NAME') }}"
    DB_USER: "{{ lookup('env','DB_USER') }}"
    DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
    DB_PORT: "{{ lookup('env','DB_PORT') }}"
    DB_HOST: "{{ lookup('env','DB_HOST') }}"
    WASM_BUILD_FOLDER: "{{ lookup('env','WASM_BUILD_FOLDER') }}"

  #Do tasks
  tasks:
    - name: Install and enable required packages
      include: tasks/packages/packages.yaml

    - name: Run database docker
      include: tasks/wasm-compiler/database.yaml

    - name: Install/Update wasm-compiler
      include: tasks/wasm-compiler/wasm-compiler.yaml

    - name: Install nginx with self-signed certs
      include: tasks/nginx/nginx.yaml
