kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: gear-node
  labels:
    app: gear-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gear-node
  template:
    metadata:
      labels:
        app: gear-node
    spec:
      containers:
        - name: gear-node
          image: sergeyfilyanin/gear-node:latest
          ports:
            - containerPort: 9944

---
kind: Service
apiVersion: v1
metadata:
  name: gear-node
  namespace: test-env
  labels:
    app: gear-node
spec:
  ports:
    - name: gear-node
      protocol: TCP
      port: 9944
      targetPort: 9944
  selector:
    app: gear-node
