[package]
name = "test-meta-io"
version = "0.1.0"
edition = "2021"

[dependencies]
scale-info.workspace = true
codec.workspace = true
gstd.workspace = true
gmeta.workspace = true
primitive-types.workspace = true
