programs:
  1:
    dapp: 'nft_marketplace'
    repo: 'non-fungible-token'
    optDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft_marketplace.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft_marketplace.meta.wasm'
    acc: 'alice'
    payload:
      adminId: '0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'
      treasuryId: '0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'
      treasuryFee: '1'
    value: NULL

  2:
    dapp: 'nft'
    repo: 'non-fungible-token'
    optDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft.meta.wasm'
    acc: 'alice'
    payload:
      name: 'test'
      symbol: 'test'
      baseUrl: 'test'
      royalties: NULL
    value: NULL

  3:
    dapp: '#nft'
    repo: 'non-fungible-token'
    optDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/non-fungible-token/releases/download/build/nft.meta.wasm'
    acc: 'alice'
    payload:
      name: 'test'
      symbol: 'test'
      baseUrl: 'test'
      royalties: NULL
    value: NULL

  4:
    dapp: 'lottery'
    repo: 'lottery'
    optDownloadUrl: 'https://github.com/gear-dapps/lottery/releases/download/build/lottery.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/lottery/releases/download/build/lottery.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

  5:
    dapp: 'dutch_auction'
    repo: 'dutch-auction'
    optDownloadUrl: 'https://github.com/gear-dapps/dutch-auction/releases/download/build/dutch_auction.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/dutch-auction/releases/download/build/dutch_auction.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

  6:
    dapp: 'escrow'
    repo: 'escrow'
    optDownloadUrl: 'https://github.com/gear-dapps/escrow/releases/download/build/escrow.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/escrow/releases/download/build/escrow.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

  7:
    dapp: 'supply_chain'
    repo: 'supply-chain'
    optDownloadUrl: 'https://github.com/gear-dapps/supply-chain/releases/download/build/supply_chain.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/supply-chain/releases/download/build/supply_chain.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

  8:
    dapp: 'rock_paper_scissors'
    repo: 'rock-paper-scissors'
    optDownloadUrl: 'https://github.com/gear-dapps/rock-paper-scissors/releases/download/build/rock_paper_scissors.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/rock-paper-scissors/releases/download/build/rock_paper_scissors.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

  9:
    dapp: 'staking'
    repo: 'staking'
    optDownloadUrl: 'https://github.com/gear-dapps/staking/releases/download/build/staking.opt.wasm'
    metaDownloadUrl: 'https://github.com/gear-dapps/staking/releases/download/build/staking.meta.wasm'
    acc: 'alice'
    payload: '0x'
    value: NULL

workflow:
  - command: uploadProgram # nft
    program: 1

  - command: uploadProgram # marketplace
    program: 3

  - command: sendMessage
    program: 1
    acc: 'alice'
    payload:
      AddNftContract: 3
    value: NULL

  - command: uploadProgram
    program: 2

  - command: uploadProgram # lottery
    program: 4

  - command: uploadProgram # dutch auction
    program: 5

workflowSingleDapp:
  nft:
    actions:
      - command: uploadProgram
        program: 2

  nft_marketplace:
    actions:
      - command: uploadProgram
        program: 1

      - command: uploadProgram
        program: 3

      - command: sendMessage
        program: 1
        acc: 'alice'
        payload:
          AddNftContract: 3
        value: NULL

  lottery:
    actions:
      - command: uploadProgram
        program: 4

  dutch_auction:
    actions:
      - command: uploadProgram
        program: 5

  escrow:
    actions:
      - command: submitCode
        program: 6

  supply_chain:
    actions:
      - command: submitCode
        program: 7

  rock_paper_scissors:
    actions:
      - command: submitCode
        program: 8

  staking:
    actions:
      - command: submitCode
        program: 9
