FROM node:16-alpine AS builder
WORKDIR /marketplace
ARG REACT_APP_NODE_ADDRESS  \
    REACT_APP_IPFS_ADDRESS  \
    REACT_APP_MARKETPLACE_NFT_CONTRACT_ADDRESS  \
    REACT_APP_MARKETPLACE_CONTRACT_ADDRESS \
    REACT_APP_IPFS_GATEWAY_ADDRESS
ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
    REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
    REACT_APP_MARKETPLACE_NFT_CONTRACT_ADDRESS=${REACT_APP_MARKETPLACE_NFT_CONTRACT_ADDRESS} \
    REACT_APP_MARKETPLACE_CONTRACT_ADDRESS=${REACT_APP_MARKETPLACE_CONTRACT_ADDRESS} \
    REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS}
COPY . /marketplace
RUN npm install --force
RUN npm run build

FROM nginx:alpine
RUN rm -vf /usr/share/nginx/html/*
COPY --from=builder /marketplace/build /usr/share/nginx/html
