kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: test-env
  name: zookeeper-testenv
  labels:
    app: zookeeper-testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-testenv
  template:
    metadata:
      labels:
        app: zookeeper-testenv
    spec:
      containers:
        - name: zookeeper-testenv
          image: zookeeper
          ports:
            - containerPort: 2181

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-testenv
  namespace: test-env
  labels:
    app: zookeeper-testenv
spec:
  ports:
  - port: 2181
    name: zookeeper-testenv
  selector:
    app: zookeeper-testenv
