FROM node:16-alpine AS builder
WORKDIR /nft
ARG REACT_APP_NODE_ADDRESS  \
    REACT_APP_IPFS_ADDRESS  \
    REACT_APP_NFT_CONTRACT_ADDRESS  \
    REACT_APP_IPFS_GATEWAY_ADDRESS
ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
    REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
    REACT_APP_NFT_CONTRACT_ADDRESS=${REACT_APP_NFT_CONTRACT_ADDRESS} \
    REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS}
COPY . /nft
RUN npm install --force
RUN npm run build

FROM nginx:alpine
RUN rm -vf /usr/share/nginx/html/*
COPY --from=builder /nft/build /usr/share/nginx/html
