name: CD events-listener

on: [workflow_dispatch]
# on:
# push:
# branches: ['do-event-listener']

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          EVENT_LISTENER_WS_PROVIDER: ${{ secrets.EVENT_LISTENER_WS_PROVIDER }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          EVENT_LISTENER_KAFKA_CLIENT_ID: ${{secrets.EVENT_LISTENER_KAFKA_CLIENT_ID}}

        with:
          directory: ./ansible
          playbook: events-listener.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.TEST_GEAR_BACKEND}}
          requirements: galaxy-requirements.yml
