name: CD events-listener

on:
  push:
    branches: [do-event-listener]
    paths:
      - website/events-listener/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-events-listener-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Build and push events-listener docker
        id: events_listener_docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/events-listener/Dockerfile
          push: true
          tags: mithriy/gear-event-listener:nightly

  Deploy:
    needs: Build-events-listener-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          EVENT_LISTENER_WS_PROVIDER: ${{ secrets.EVENT_LISTENER_WS_PROVIDER }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          EVENT_LISTENER_KAFKA_CLIENT_ID: ${{secrets.EVENT_LISTENER_KAFKA_CLIENT_ID}}

        with:
          directory: ./ansible
          playbook: events-listener.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.TEST_GEAR_BACKEND}}
          requirements: galaxy-requirements.yml
