name: CD events-listener

on: [workflow_dispatch]
# on:
# push:
# branches: ['do-event-listener']

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: staging-events-listener
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          WS_PROVIDER: ${{ secrets.WS_PROVIDER }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_CLIENT_ID: ${{secrets.KAFKA_CLIENT_ID}}

        with:
          directory: ./ansible/tasks/events-listener
          playbook: events-listener.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.HOST}}
          requirements: ../../galaxy-requirements.yml
