name: CD frontend

on:
  push:
    branches: [master, do-event-listener]
    paths:
      - website/frontend/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy-frontend:
    runs-on: ubuntu-latest
    environment: staging_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          API_GATEWAY_ADDRESS: ${{ secrets.API_GATEWAY_ADDRESS }}
          WS_PROVIDER: ${{ secrets.WS_PROVIDER }}
          WASM_COMPILER_ADDRESS: ${{ secrets.WASM_COMPILER_ADDRESS }}
        with:
          # Required, playbook filepath
          directory: ./ansible/tasks/frontend
          playbook: frontend.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.STAGING_HOST}}
          requirements: galaxy-requirements.yml
