name: CD

on:
  push:
    branches: [master, do-clear-db-cd]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get commit message
        run: echo ${{ github.event.head_commit.message }}

      - name: Check commit message
        if: contains( github.event.head_commit.message, 'frontend' )
        run: |
          'echo github.event.head_commit.message'

      - name: Log when unchanged
        if: "!contains( github.event.head_commit.message, 'frontend' )"
        run: 'echo "No version change :/"'
    # - name: Run playbook
    #   uses: dawidd6/action-ansible-playbook@v2
    #   env:
    #     GITHUB_CLIENT_ID: ${{ secrets.GTHUB_CLIENT_ID }}
    #     NODE_ADDRESS: ${{secrets.GEAR_BACKEND_NODE}}
    #     TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
    #     REACT_APP_RRT: ${{secrets.REACT_APP_RRT}}
    #   with:
    #     # Required, playbook filepath
    #     directory: ./ansible/tasks
    #     playbook: frontend/frontend.yaml
    #     # Optional, SSH private key
    #     key: ${{secrets.SSH_PRIVATE_KEY}}
    #     # Optional, literal inventory file contents
    #     requirements: galaxy-requirements.yml
