name: CD-get-balance

on:
  push:
    branches: [master]
    paths:
      - website/get-balance/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/get-balance/Dockerfile
          push: true
          tags: mithriy/gear-get-balance:nightly

  Deploy:
    needs: Build-backend-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_NAME: ${{ secrets.TEST_BALANCE_DB_NAME }}
          DB_USER: ${{ secrets.TEST_BALANCE_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_BALANCE_DB_PASSWORD }}
          DB_PORT: ${{ secrets.TEST_BALANCE_DB_PORT }}
          DB_HOST: ${{ secrets.TEST_BALANCE_DB_HOST }}
          WS_PROVIDER: ${{ secrets.TEST_BALANCE_WS_PROVIDER }}
          ROOT_ACCOUNT_SEED: ${{secrets.SUDO_SEED}}
          TEST_ACCOUNT_SEED: ${{secrets.TEST_ACCOUNT_SEED}}
          TEST_ACCOUNT_BALANCE: ${{secrets.SITE_ACCOUNT_BALANCE}}
          TEST_BALANCE_VALUE: ${{secrets.TEST_BALANCE_VALUE}}
        with:
          # Required, playbook filepath
          directory: ./ansible
          playbook: get-balance.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.GEAR_BACKEND_NODE}}
          requirements: galaxy-requirements.yml
