name: CD new backend

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_PORT: ${{ secrets.KAFKA_PORT}}
          KAFKA_HOST_NAME: ${{ secrets.KAFKA_HOST_NAME }}
          API_BACKEND_KAFKA_CLIENT_ID: ${{ secrets.API_BACKEND_KAFKA_CLIENT_ID }}
          API_BACKEND_KAFKA_GROUP_ID: ${{ secrets.API_BACKEND_KAFKA_GROUP_ID }}
          API_BACKEND_PORT: ${{ secrets.API_BACKEND_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATA_STORAGE_KAFKA_CLIENT_ID: ${{ secrets.DATA_STORAGE_KAFKA_CLIENT_ID }}
          DATA_STORAGE_KAFKA_GROUP_ID: ${{ secrets.DATA_STORAGE_KAFKA_GROUP_ID }}

        with:
          directory: ./ansible
          playbook: new-backend.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{secrets.TEST_GEAR_BACKEND}}
          requirements: galaxy-requirements.yml
