name: CD-test-balance

on:
  push:
    branches: [master, do-event-listener]
    paths:
      - website/test-balance/**

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/test-balance/Dockerfile
          push: true
          tags: mithriy/gear-test-balance:nightly

  Deploy:
    needs: Build-backend-docker
    runs-on: ubuntu-latest
    environment: staging_test_balance_service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          WS_PROVIDER: ${{ secrets.WS_PROVIDER }}
          ROOT_ACCOUNT_SEED: ${{secrets.ROOT_ACCOUNT_SEED}}
          TEST_ACCOUNT_SEED: ${{secrets.TEST_ACCOUNT_SEED}}
          TEST_ACCOUNT_BALANCE: ${{secrets.TEST_ACCOUNT_BALANCE}}
          TEST_BALANCE_VALUE: ${{secrets.TEST_BALANCE_VALUE}}
          KAFKA_CLIENT_ID: ${{secrets.KAFKA_CLIENT_ID}}
          KAFKA_GROUP_ID: ${{secrets.KAFKA_GROUP_ID}}
          KAFKA_BROKERS: ${{secrets.KAFKA_BROKERS}}
        with:
          # Required, playbook filepath
          directory: ./ansible/tasks/new-backend
          playbook: test-balance.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.HOST}}
          requirements: ../../galaxy-requirements.yml
