name: 'CI-apis'

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]
  workflow_dispatch:
    inputs:
      lib:
        description: 'The library to build'
        required: true
        type: choice
        options:
          - gear-api
          - vara-eth-api

env:
  BINARYEN_VERSION: version_111

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js

      - name: 'Run linter'
        run: yarn check:apis

  changes:
    runs-on: ubuntu-latest
    outputs:
      gear-api: ${{ steps.run.outputs.gear-api }}
      vara-eth-api: ${{ steps.run.outputs.vara-eth-api }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Detect changes'
        id: changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            gear-api:
              - 'apis/gear/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - package.json
              - yarn.lock
            vara-eth-api:
              - 'apis/vara-eth/**'
              - package.json
              - yarn.lock

      - name: "Detect what should be running"
        id: run
        run: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              INPUT="${{ github.event.inputs.lib }}"
              [[ "$INPUT" == "gear-api" ]] && echo "gear-api=true" >> "$GITHUB_OUTPUT" || echo "gear-api=false" >> "$GITHUB_OUTPUT"
              [[ "$INPUT" == "vara-eth-api" ]] && echo "vara-eth-api=true" >> "$GITHUB_OUTPUT" || echo "vara-eth-api=false" >> "$GITHUB_OUTPUT"
            else
              echo "gear-api=${{ steps.changes.outputs.gear-api }}" >> "$GITHUB_OUTPUT"
              echo "vara-eth-api=${{ steps.changes.outputs.vara-eth-api }}" >> "$GITHUB_OUTPUT"
            fi

  build-gear-api:
    runs-on: ubuntu-latest
    needs: ["changes"]
    if: ${{ needs.changes.outputs.gear-api == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js @gear-js/api

      - name: 'Build gear api'
        run: yarn build:gear-api

  build-vara-eth-api:
    runs-on: ubuntu-latest
    needs: ["changes"]
    if: ${{ needs.changes.outputs.vara-eth-api == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js @vara-eth/api

      - name: 'Build vara-eth api'
        run: yarn build:vara-eth-api

  test-gear-api:
    needs: ["build-gear-api"]
    runs-on: ubuntu-24.04
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt, llvm-tools, rust-src

      - name: 'Install: binaryen'
        run: |
          wget -c https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN_VERSION/binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz -O - | tar -xz -C .
          sudo cp binaryen-$BINARYEN_VERSION/bin/wasm-opt /usr/bin/

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js @gear-js/api

      - name: 'Prepare: build programs'
        run: cargo build --release

      - name: 'Prepare: download Gear node'
        run: |
          wget -O ./gear https://github.com/gear-tech/gear/releases/download/build/gear
          chmod +x gear

      - name: 'Prepare: run Gear node'
        run: |
          nohup ./gear --dev --execution=wasm --tmp --unsafe-rpc-external --rpc-methods Unsafe --rpc-cors all &

      - name: 'Prepare: sleep 3 min'
        run: sleep 180

      - name: 'Test: run'
        run: yarn test:gear-api
        env:
          SKIP_RUN_NODE: true
          SKIP_BUILD: true

  test-varaeth-api:
    needs: ["build-vara-eth-api"]
    runs-on: ubuntu-24.04
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 24.x'
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt, llvm-tools, rust-src

      - name: 'Install: binaryen'
        run: |
          wget -c https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN_VERSION/binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz -O - | tar -xz -C .
          sudo cp binaryen-$BINARYEN_VERSION/bin/wasm-opt /usr/bin/

      - name: 'Install: Foundry'
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.7.0

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js @vara-eth/api

      - name: 'Download ethexe bin from gear releases'
        working-directory: apis/vara-eth
        run: |
          wget -O ./ethexe https://github.com/gear-tech/gear/releases/download/build/ethexe
          chmod +x ethexe

      - name: 'Build programs'
        working-directory: apis/vara-eth
        run: cargo b -r

      - name: 'Compile contracts'
        working-directory: apis/vara-eth
        run: forge compile

      - name: 'Test: run'
        working-directory: apis/vara-eth
        run: yarn test
        env:
          PATH_TO_ETHEXE: ./ethexe

      - name: 'Upload vara-eth node log'
        uses: actions/upload-artifact@v7
        with:
          name: vara-eth-log
          path: apis/vara-eth/vara-eth.log
          if-no-files-found: ignore
          retention-days: 1
