name: 'CI-apis'

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - "apis/**"
      - package.json
      - Cargo.toml
      - Cargo.lock
  workflow_dispatch:
    inputs:
      lib:
        description: 'The library to build'
        required: true
        type: choice
        options:
          - gear-api
          - vara-eth-api

env:
  BINARYEN_VERSION: version_111

jobs:
  guard:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - run: echo "Not a draft PR, proceeding"

  lint:
    runs-on: ubuntu-latest
    needs: [guard]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-command: pnpm install --frozen-lockfile

      - name: 'Run linter'
        run: pnpm run check:apis

  changes:
    runs-on: ubuntu-latest
    needs: [guard]
    outputs:
      gear-api: ${{ steps.run.outputs.gear-api }}
      vara-eth-api: ${{ steps.run.outputs.vara-eth-api }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v7

      - name: 'Detect changes'
        id: changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            gear-api:
              - 'apis/gear/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - package.json
            vara-eth-api:
              - 'apis/vara-eth/**'
              - package.json

      - name: "Detect what should be running"
        id: run
        run: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              INPUT="${{ github.event.inputs.lib }}"
              [[ "$INPUT" == "gear-api" ]] && echo "gear-api=true" >> "$GITHUB_OUTPUT" || echo "gear-api=false" >> "$GITHUB_OUTPUT"
              [[ "$INPUT" == "vara-eth-api" ]] && echo "vara-eth-api=true" >> "$GITHUB_OUTPUT" || echo "vara-eth-api=false" >> "$GITHUB_OUTPUT"
            else
              echo "gear-api=${{ steps.changes.outputs.gear-api }}" >> "$GITHUB_OUTPUT"
              echo "vara-eth-api=${{ steps.changes.outputs.vara-eth-api }}" >> "$GITHUB_OUTPUT"
            fi

  build-gear-api:
    runs-on: ubuntu-latest
    needs: ["changes"]
    if: ${{ needs.changes.outputs.gear-api == 'true' || inputs.force }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-command: pnpm install --frozen-lockfile

      - name: 'Build gear api'
        run: pnpm run build:gear-api

  build-vara-eth-api:
    runs-on: ubuntu-latest
    needs: ["changes"]
    if: ${{ needs.changes.outputs.vara-eth-api == 'true' || inputs.force }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-command: pnpm install --frozen-lockfile

      - name: 'Build vara-eth api'
        run: pnpm run build:vara-eth-api

  test-gear-api:
    needs: ["build-gear-api"]
    runs-on: ubuntu-24.04
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-command: pnpm install --frozen-lockfile

      - name: Set up Rust
        uses: gear-tech/gear/.github/actions/install-rust@master

      - name: Install Binaryen
        uses: ./.github/actions/install-binaryen

      - name: 'Prepare: build programs'
        run: cargo build --release

      - name: 'Prepare: download Gear node'
        run: |
          wget -O ./gear https://github.com/gear-tech/gear/releases/download/build/gear
          chmod +x gear

      - name: 'Prepare: run Gear node'
        run: |
          nohup ./gear --dev --execution=wasm --tmp --unsafe-rpc-external --rpc-methods Unsafe --rpc-cors all &

      - name: 'Prepare: sleep 3 min'
        run: sleep 180

      - name: 'Test: run'
        run: pnpm run test:gear-api
        env:
          SKIP_RUN_NODE: true
          SKIP_BUILD: true

  test-varaeth-api:
    needs: ["build-vara-eth-api"]
    runs-on: ubuntu-24.04
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          node-version: 24.x
          install-command: pnpm install --frozen-lockfile

      - name: Set up Rust
        uses: gear-tech/gear/.github/actions/install-rust@master

      - name: Install Binaryen
        uses: ./.github/actions/install-binaryen

      - name: 'Install: Foundry'
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.7.0

      - name: 'Download ethexe bin from gear releases'
        working-directory: apis/vara-eth
        run: |
          wget -O ./ethexe https://github.com/gear-tech/gear/releases/download/build/ethexe
          chmod +x ethexe

      - name: 'Build programs'
        working-directory: apis/vara-eth
        run: cargo b -r

      - name: 'Compile contracts'
        working-directory: apis/vara-eth
        run: forge compile

      - name: 'Build @gear-js/api'
        working-directory: apis/gear
        run: pnpm run build

      - name: 'Test: run'
        working-directory: apis/vara-eth
        run: pnpm run test
        env:
          PATH_TO_ETHEXE: ./ethexe

      - name: 'Upload vara-eth node log'
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: vara-eth-log
          path: apis/vara-eth/vara-eth.log
          if-no-files-found: ignore
          retention-days: 1
