name: CI Gear-apps

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: ['master']
    paths:
      - apps/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  wait-previous-run:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1 # please read security note
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  conditional_job_check_files:
    runs-on: ubuntu-latest
    # Declare outputs for next jobs
    outputs:
      nft_changed: ${{ steps.check_file_changed.outputs.nft_changed }}
      marketplace_changed: ${{ steps.check_file_changed.outputs.marketplace_changed }}
      lottery_changed: ${{ steps.check_file_changed.outputs.lottery_changed }}
      escrow_changed: ${{ steps.check_file_changed.outputs.escrow_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under nft/ has changed (added, modified, deleted)
        $SourceDiffNft = $diff | Where-Object { $_ -match '^apps/nft/' }
        $HasDiffNft = $SourceDiffNft.Length -gt 0

        # Check if a file under marketplace/ has changed (added, modified, deleted)
        $SourceDiffMarketplace = $diff | Where-Object { $_ -match '^apps/marketplace/' }
        $HasDiffMarketplace = $SourceDiffMarketplace.Length -gt 0

        # Check if a file under lottery/ has changed (added, modified, deleted)
        $SourceDiffLottery = $diff | Where-Object { $_ -match '^apps/lottery/' }
        $HasDiffLottery = $SourceDiffLottery.Length -gt 0

        # Check if a file under escrow/ has changed (added, modified, deleted)
        $SourceDiffEscrow = $diff | Where-Object { $_ -match '^apps/escrow/' }
        $HasDiffEscrow = $SourceDiffEscrow.Length -gt 0

        # Set the output named "nft_changed"
        Write-Host "::set-output name=nft_changed::$HasDiffNft"
        Write-Host "::set-output name=marketplace_changed::$HasDiffMarketplace"
        Write-Host "::set-output name=lottery_changed::$HasDiffLottery"
        Write-Host "::set-output name=escrow_changed::$HasDiffEscrow"

  build-marketplace-image:
    runs-on: ubuntu-latest
    needs: [wait-previous-run,conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.marketplace_changed == 'True'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build MarketPlace Docker image
        uses: docker/build-push-action@master
        with:
          file: apps/marketplace/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-marketplace:ci
          build-args: |
            REACT_APP_NODE_ADDRESS=${{ secrets.REACT_APP_NODE_ADDRESS }}
            REACT_APP_IPFS_ADDRESS=${{ secrets.REACT_APP_IPFS_ADDRESS }}
            REACT_APP_MARKETPLACE_NFT_CONTRACT_ADDRESS=${{ secrets.REACT_APP_MARKETPLACE_NFT_CONTRACT_ADDRESS }}
            REACT_APP_MARKETPLACE_CONTRACT_ADDRESS=${{ secrets.REACT_APP_MARKETPLACE_CONTRACT_ADDRESS }}
            REACT_APP_IPFS_GATEWAY_ADDRESS=${{ secrets.REACT_APP_IPFS_GATEWAY_ADDRESS }}

  build-nft-image:
    runs-on: ubuntu-latest
    needs: [wait-previous-run,conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.nft_changed == 'True'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Nft Docker image
        uses: docker/build-push-action@master
        with:
          file: apps/nft/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nft:ci
          build-args: |
            REACT_APP_NODE_ADDRESS=${{ secrets.REACT_APP_NODE_ADDRESS }}
            REACT_APP_IPFS_ADDRESS=${{ secrets.REACT_APP_IPFS_ADDRESS }}
            REACT_APP_NFT_CONTRACT_ADDRESS=${{ secrets.REACT_APP_NFT_CONTRACT_ADDRESS }}
            REACT_APP_IPFS_GATEWAY_ADDRESS=${{ secrets.REACT_APP_IPFS_GATEWAY_ADDRESS }}


  build-lottery-image:
    runs-on: ubuntu-latest
    needs: [wait-previous-run,conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.lottery_changed == 'True'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Lottery Docker image
        uses: docker/build-push-action@master
        with:
          file: apps/lottery/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-lottery:ci
          build-args: |
            REACT_APP_NODE_ADDRESS=${{ secrets.REACT_APP_NODE_ADDRESS }}
            REACT_APP_LOTTERY_CONTRACT_ADDRESS=${{ secrets.REACT_APP_LOTTERY_CONTRACT_ADDRESS }}

  build-escrow-image:
    runs-on: ubuntu-latest
    needs: [wait-previous-run,conditional_job_check_files]
    if: needs.conditional_job_check_files.outputs.escrow_changed == 'True'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Escrow Docker image
        uses: docker/build-push-action@master
        with:
          file: apps/escrow/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-escrow:ci
          build-args: |
            REACT_APP_NODE_ADDRESS=${{ secrets.REACT_APP_NODE_ADDRESS }}
