name: 'CI'

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]
  workflow_dispatch:

env:
  BINARYEN_VERSION: version_111

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Run linter'
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build all packages'
        run: yarn build

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build @gear-js/frontend-configs'
        run: yarn build:frontend-configs

      - name: 'gear-ui: Run tests'
        run: yarn test:ui

  test-txwrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Test: run'
        run: yarn test:txwrapper

  test-util:
    runs-on: ubuntu-22.04
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js-util gear-js

      - name: 'Test: run'
        run: yarn test:gear-js-util
