name: 'CI'

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]
    paths:
      - "utils/**"
      - "tools/**"
  workflow_dispatch:

env:
  BINARYEN_VERSION: version_111

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      utils-ui: ${{ steps.changes.outputs.utils-ui }}
      utils: ${{ steps.changes.outputs.utils }}
      tools: ${{ steps.changes.outputs.tools }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            utils-ui:
              - 'utils/frontend-configs/**'
              - 'utils/gear-hooks/**'
              - 'utils/gear-ui/**'
              - 'utils/sails-payload-form/**'
              - 'utils/vara-ui/**'
              - 'utils/wallet-connect/**'
            tools:
              - 'tools/**'
            utils:
              - 'utils/util/**'
              - 'utils/logger/**'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Run linter'
        run: yarn lint

  build-ui-utils:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ steps.changes.outputs.utils-ui == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: yarn

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build frontend-configs'
        run: yarn build:frontend-configs

      - name: 'Build gear-hooks'
        run: yarn build:hooks

      - name: 'Build gear-ui'
        run: yarn build:ui

      - name: 'Build sails-payload-form'
        run: yarn build:sails-payload-form

      - name: 'Build vara-ui'
        run: yarn build:vara-ui

      - name: 'Build wallet-connect'
        run: yarn build:wallet-connect

      - name: "Build frontends"
        run: |
            yarn lerna run build --scope @gear-js/api --scope @vara-eth/api
            yarn lerna run build --scope gear-idea-frontend varaeth-idea-frontend

  test-ui:
    runs-on: ubuntu-latest
    needs: [build-ui-utils]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build @gear-js/frontend-configs'
        run: yarn build:frontend-configs

      - name: 'gear-ui: Run tests'
        run: yarn test:ui

  build-tools:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ steps.changes.outputs.tools == 'true' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install Node.js 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: yarn

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build'
        run: yarn build:tools

  test-txwrapper:
    runs-on: ubuntu-latest
    needs: [build-tools]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1

      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Test: run'
        run: yarn test:txwrapper

  test-util:
    runs-on: ubuntu-22.04
    needs: [build-tools]
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Install: NodeJS 20.x'
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: 'Install dependencies'
        run: yarn workspaces focus gear-js-util gear-js

      - name: 'Test: run'
        run: yarn test:gear-js-util
