name: 'CI'

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      force:
        type: boolean
        default: false
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - "utils/**"
      - "tools/**"
      - package.json
  workflow_dispatch:

env:
  BINARYEN_VERSION: version_111

jobs:
  guard:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - run: echo "Not a draft PR, proceeding"

  changes:
    runs-on: ubuntu-latest
    needs: [guard]
    outputs:
      utils-ui: ${{ steps.changes.outputs.utils-ui }}
      utils: ${{ steps.changes.outputs.utils }}
      tools: ${{ steps.changes.outputs.tools }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            utils-ui:
              - 'utils/frontend-configs/**'
              - 'utils/gear-hooks/**'
              - 'utils/gear-ui/**'
              - 'utils/sails-payload-form/**'
              - 'utils/vara-ui/**'
              - 'utils/wallet-connect/**'
              - package.json
            tools:
              - 'tools/**'
              - package.json
            utils:
              - 'utils/util/**'
              - 'utils/logger/**'
              - package.json

  lint:
    runs-on: ubuntu-latest
    needs: [guard]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: 'Run linter'
        run: yarn lint

  build-ui-utils:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.utils-ui == 'true' || inputs.force }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: 'Build frontend-configs'
        run: yarn build:frontend-configs

      - name: 'Build gear-hooks'
        run: yarn build:hooks

      - name: 'Build gear-ui'
        run: yarn build:ui

      - name: 'Build sails-payload-form'
        run: yarn build:sails-payload-form

      - name: 'Build vara-ui'
        run: yarn build:vara-ui

      - name: 'Build wallet-connect'
        run: yarn build:wallet-connect

      - name: "Build frontends"
        run: |
            yarn lerna run build --scope @gear-js/api --scope @vara-eth/api
            yarn lerna run build --scope gear-idea-frontend --scope varaeth-idea-frontend

  test-ui:
    runs-on: ubuntu-latest
    needs: [build-ui-utils]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: 'Build @gear-js/frontend-configs'
        run: yarn build:frontend-configs

      - name: 'gear-ui: Run tests'
        run: yarn test:ui

  build-tools:
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.tools == 'true' || inputs.force }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: 'Build'
        run: yarn build:tools

  test-txwrapper:
    runs-on: ubuntu-latest
    needs: [build-tools]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: 'Test: run'
        run: yarn test:txwrapper

  test-util:
    runs-on: ubuntu-22.04
    needs: [build-tools]
    env:
      RUSTUP_HOME: /tmp/rustup_home
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-command: yarn workspaces focus gear-js-util gear-js

      - name: 'Test: run'
        run: yarn test:gear-js-util
