name: build-api-gateway-docker

on:
  push:
    branches: [do-event-listener]
    paths:
      - website/api-gateway/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-api-backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Build and push api-backend
        id: api_backend_docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/api-gateway/Dockerfile
          push: true
          tags: mithriy/gear-api-gateway:nightly
