name: build-events-listener-docker

on:
  push:
    branches: [master, do-event-listener]
    paths:
      - website/events-listener/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build-events-listener-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: Build and push events-listener docker
        id: events_listener_docker_build
        uses: docker/build-push-action@v2
        with:
          file: website/events-listener/Dockerfile
          push: true
          tags: mithriy/gear-event-listener:nightly
