name: production.data-storage-CD

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    needs: build-data-storage-docker
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_NAME: ${{ secrets.DATA_STORAGE_DB_NAME }}
          DB_USER: ${{ secrets.DATA_STORAGE_DB_USER }}
          DB_PASSWORD: ${{ secrets.DATA_STORAGE_DB_PASSWORD }}
          KAFKA_CLIENT_ID: ${{ secrets.DATA_STORAGE_KAFKA_CLIENT_ID }}
          KAFKA_GROUP_ID: ${{ secrets.DATA_STORAGE_KAFKA_GROUP_ID }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}

        with:
          directory: ./ansible/tasks/data-storage
          playbook: data-storage.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{secrets.PROD_HOST}}
          requirements: ../../galaxy-requirements.yml
