name: production.events-listener-CD

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    needs: build-events-listener-docker
    environment: staging-events-listener
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          WS_PROVIDER: ${{ secrets.EVENTS_LISTENER_TESTNET_WS_PROVIDER }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_CLIENT_ID: ${{ secrets.EVENTS_LISTENER_TESTNET_KAFKA_CLIENT_ID }}

        with:
          directory: ./ansible/tasks/events-listener
          playbook: events-listener.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ secrets.PROD_HOST }}
          requirements: ../../galaxy-requirements.yml
