name: production.api-gateway-CD

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_CLIENT_ID: ${{ secrets.API_GATEWAY_KAFKA_CLIENT_ID }}
          KAFKA_GROUP_ID: ${{ secrets.API_GATEWAY_KAFKA_GROUP_ID }}
          KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
          CAPTCH_SECRET: ${{ secrets.CAPTCH_SECRET }}

        with:
          directory: ./ansible/tasks/api-gateway
          playbook: api-gateway.yaml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{secrets.PROD_HOST}}
          requirements: ../../galaxy-requirements.yml
