name: production.test-balance-CD

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    needs: Build-backend-docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          KAFKA_BROKERS: ${{secrets.KAFKA_BROKERS}}
          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_BALANCE_DB_NAME }}
          DB_USER: ${{ secrets.TEST_BALANCE_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_BALANCE_DB_PASSWORD }}
          TEST_ACCOUNT_SEED: ${{ secrets.TEST_BALANCE_ACCOUNT_SEED }}
          KAFKA_CLIENT_ID_TESTNET: ${{ secrets.TEST_BALANCE_KAFKA_CLIENT_ID_TESTNET }}
          KAFKA_GROUP_ID_TESTNET: ${{ secrets.TEST_BALANCE_KAFKA_GROUP_ID_TESTNET }}
          WS_PROVIDER_TESTNET: ${{ secrets.TEST_BALANCE_WS_PROVIDER_TESTNET }}
          ROOT_ACCOUNT_SEED_TESTNET: ${{ secrets.TEST_BALANCE_ROOT_ACCOUNT_SEED_TESTNET }}
          TEST_ACCOUNT_BALANCE_TESTNET: ${{ secrets.TEST_BALANCE_ACCOUNT_BALANCE_TESTNET }}
          TEST_BALANCE_VALUE_TESTNET: ${{ secrets.TEST_BALANCE_VALUE_TESTNET }}
          KAFKA_CLIENT_ID_WRSH: ${{ secrets.TEST_BALANCE_KAFKA_CLIENT_ID_WRSH }}
          KAFKA_GROUP_ID_WRSH: ${{ secrets.TEST_BALANCE_KAFKA_GROUP_ID_WRSH }}
          WS_PROVIDER_WRSH: ${{ secrets.TEST_BALANCE_WS_PROVIDER_WRSH }}
          ROOT_ACCOUNT_SEED_WRSH: ${{ secrets.TEST_BALANCE_ROOT_ACCOUNT_SEED_WRSH }}
          TEST_ACCOUNT_BALANCE_WRSH: ${{ secrets.TEST_BALANCE_ACCOUNT_BALANCE_WRSH }}
          TEST_BALANCE_VALUE_WRSH: ${{ secrets.TEST_BALANCE_VALUE_WRSH }}

        with:
          # Required, playbook filepath
          directory: ./ansible/tasks/test-balance
          playbook: test-balance.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.PROD_HOST}}
          requirements: ../../galaxy-requirements.yml
