name: CD test-balance

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  Deploy:
    needs: Build-backend-docker
    runs-on: ubuntu-latest
    environment: staging_test_balance_service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          WS_PROVIDER: ${{ secrets.WS_PROVIDER }}
          ROOT_ACCOUNT_SEED: ${{secrets.ROOT_ACCOUNT_SEED}}
          TEST_ACCOUNT_SEED: ${{secrets.TEST_ACCOUNT_SEED}}
          TEST_ACCOUNT_BALANCE: ${{secrets.TEST_ACCOUNT_BALANCE}}
          TEST_BALANCE_VALUE: ${{secrets.TEST_BALANCE_VALUE}}
          KAFKA_CLIENT_ID: ${{secrets.KAFKA_CLIENT_ID}}
          KAFKA_GROUP_ID: ${{secrets.KAFKA_GROUP_ID}}
          KAFKA_BROKERS: ${{secrets.KAFKA_BROKERS}}
        with:
          # Required, playbook filepath
          directory: ./ansible/tasks/test-balance
          playbook: test-balance.yaml
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.PROD_HOST}}
          requirements: ../../galaxy-requirements.yml
