name: 'Gear Idea Release'

on:
  push:
    branches: ['main', 'stable']
    paths:
      - idea/gear/**
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Service to release
        options:
          - frontend
          - faucet
          - squid
          - meta-storage
          - explorer
          - all
          - backend
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  set-env-tag:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get_env.outputs.environment }}
    permissions:
      contents: read
    steps:
      - name: Get environment
        id: get_env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/stable" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.should-build.outputs.frontend }}
      faucet: ${{ steps.should-build.outputs.faucet }}
      meta-storage: ${{ steps.should-build.outputs.meta-storage }}
      squid: ${{ steps.should-build.outputs.squid }}
      explorer: ${{ steps.should-build.outputs.explorer }}
    steps:
      - uses: actions/checkout@v6

      - name: Detect file changes
        id: changes
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/stable' }}
        uses: dorny/paths-filter@v4
        with:
          filters: |
            frontend:
              - idea/gear/frontend/**
            faucet:
              - idea/gear/faucet/**
              - idea/gear/common/**
              - idea/gear/indexer-db/**
            meta-storage:
              - idea/gear/meta-storage/**
              - idea/gear/common/**
            squid:
              - idea/gear/squid/**
              - idea/gear/common/**
              - idea/gear/indexer-db/**
            explorer:
              - idea/gear/explorer/**
              - idea/gear/common/**
              - idea/gear/indexer-db/**

      - name: Determine what should be built
        id: should-build
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            INPUT="${{ github.event.inputs.service }}"
            [[ "$INPUT" == "frontend" || "$INPUT" == "all" ]] && echo "frontend=true" >> "$GITHUB_OUTPUT" || echo "frontend=false" >> "$GITHUB_OUTPUT"
            [[ "$INPUT" == "faucet" || "$INPUT" == "all" || "$INPUT" == "backend" ]] && echo "faucet=true" >> "$GITHUB_OUTPUT" || echo "faucet=false" >> "$GITHUB_OUTPUT"
            [[ "$INPUT" == "meta-storage" || "$INPUT" == "all" || "$INPUT" == "backend" ]] && echo "meta-storage=true" >> "$GITHUB_OUTPUT" || echo "meta-storage=false" >> "$GITHUB_OUTPUT"
            [[ "$INPUT" == "squid" || "$INPUT" == "all" || "$INPUT" == "backend" ]] && echo "squid=true" >> "$GITHUB_OUTPUT" || echo "squid=false" >> "$GITHUB_OUTPUT"
            [[ "$INPUT" == "explorer" || "$INPUT" == "all" || "$INPUT" == "backend" ]] && echo "explorer=true" >> "$GITHUB_OUTPUT" || echo "explorer=false" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" == "refs/heads/stable" ]]; then
            echo "frontend=true" >> "$GITHUB_OUTPUT"
            echo "faucet=true" >> "$GITHUB_OUTPUT"
            echo "meta-storage=true" >> "$GITHUB_OUTPUT"
            echo "squid=true" >> "$GITHUB_OUTPUT"
            echo "explorer=true" >> "$GITHUB_OUTPUT"
          else
            echo "frontend=${{ steps.changes.outputs.frontend }}" >> "$GITHUB_OUTPUT"
            echo "faucet=${{ steps.changes.outputs.faucet }}" >> "$GITHUB_OUTPUT"
            echo "meta-storage=${{ steps.changes.outputs.meta-storage }}" >> "$GITHUB_OUTPUT"
            echo "squid=${{ steps.changes.outputs.squid }}" >> "$GITHUB_OUTPUT"
            echo "explorer=${{ steps.changes.outputs.explorer }}" >> "$GITHUB_OUTPUT"
          fi

  build-frontend-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "gear-idea-frontend" Docker image
        uses: docker/build-push-action@master
        with:
          file: idea/gear/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-frontend:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-frontend:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}
          build-args: |
            VITE_NODE_ADDRESS=${{ secrets.REACT_APP_NODE_ADDRESS }}
            VITE_DEFAULT_TRANSFER_BALANCE_VALUE=${{ secrets.REACT_APP_DEFAULT_TRANSFER_BALANCE_VALUE }}
            VITE_TURNSTILE_SITEKEY=${{ secrets.VITE_TURNSTILE_SITEKEY }}
            VITE_NODES_API_URL=${{ secrets.REACT_APP_DEFAULT_NODES_URL }}
            VITE_FAUCET_API_URL=${{ secrets.VITE_FAUCET_API_URL }}
            VITE_METADATA_STORAGE_API_URL=${{ secrets.VITE_METADATA_STORAGE_API_URL }}
            VITE_MAINNET_VOUCHERS_API_URL=${{ secrets.VITE_MAINNET_VOUCHERS_API_URL }}
            VITE_TESTNET_VOUCHERS_API_URL=${{ secrets.VITE_TESTNET_VOUCHERS_API_URL }}
            VITE_INDEXER_API_URL=${{ secrets.VITE_INDEXER_API_URL }}
            VITE_TESTNET_DNS_API_URL=${{ secrets.VITE_TESTNET_DNS_API_URL }}
            VITE_MAINNET_DNS_API_URL=${{ secrets.VITE_MAINNET_DNS_API_URL }}
            VITE_CODE_VERIFIER_API_URL=${{ secrets.VITE_CODE_VERIFIER_API_URL }}
            VITE_VFT_WHITELIST_API_URL=${{ secrets.VITE_VFT_WHITELIST_API_URL }}

  build-faucet-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.faucet == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "gear-idea-faucet" Docker image
        uses: docker/build-push-action@master
        with:
          file: idea/gear/faucet/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-faucet:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-faucet:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}

  build-meta-storage-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs['meta-storage'] == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "gear-idea-meta-storage" image
        uses: docker/build-push-action@master
        with:
          file: idea/gear/meta-storage/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-meta-storage:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-meta-storage:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}

  build-squid-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.squid == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "gear-idea-squid" image
        uses: docker/build-push-action@master
        with:
          file: idea/gear/squid/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-squid:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-squid:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}

  build-explorer-image:
    runs-on: ubuntu-latest
    needs: [set-env-tag, check-changes]
    if: ${{ needs.check-changes.outputs.explorer == 'true' }}
    environment: ${{ needs.set-env-tag.outputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "gear-idea-explorer" image
        uses: docker/build-push-action@master
        with:
          file: idea/gear/explorer/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-explorer:${{ needs.set-env-tag.outputs.environment }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gear-idea-explorer:${{ needs.set-env-tag.outputs.environment }}-${{ github.sha }}

  deploy-frontend:
    needs: [set-env-tag, build-frontend-image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment frontend-nginx -n ${{ needs.set-env-tag.outputs.environment == 'production' && 'prod-idea' || 'dev-1' }}

  deploy-faucet:
    needs: [set-env-tag, build-faucet-image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment faucet -n ${{ needs.set-env-tag.outputs.environment == 'production' && 'prod-idea' || 'dev-1' }}

  deploy-meta-storage:
    needs: [set-env-tag, build-meta-storage-image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment ${{ needs.set-env-tag.outputs.environment == 'production' && 'meta-storage-main' || 'meta-storage' }} -n ${{ needs.set-env-tag.outputs.environment == 'production' && 'prod-idea' || 'dev-1' }}

  deploy-squid:
    needs: [set-env-tag, build-squid-image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get deployment targets
        id: targets
        run: |
          if [ "${{ needs.set-env-tag.outputs.environment }}" == "production" ]; then
            echo "deployments=squid-testnet-v2 squid-mainnet-v2" >> $GITHUB_OUTPUT
            echo "namespace=prod-idea" >> $GITHUB_OUTPUT
          else
            echo "deployments=squid-testnet-v2" >> $GITHUB_OUTPUT
            echo "namespace=dev-1" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment ${{ steps.targets.outputs.deployments }} -n ${{ steps.targets.outputs.namespace }}

  deploy-explorer:
    needs: [set-env-tag, build-explorer-image]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment explorer -n ${{ needs.set-env-tag.outputs.environment == 'production' && 'prod-idea' || 'dev-1' }}
