name: Build and Deploy Vara.Eth Idea

on:
  push:
    branches: [main, master]
    paths:
      - 'idea/vara-eth/**'
    tags: ["vara-eth-idea-v*"]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options:
          - dev
          - stg
          - prod
      deploy_frontend:
        type: boolean
        description: Deploy frontend
        default: true
      deploy_indexer:
        type: boolean
        description: Deploy indexer (mainnet + testnet)
        default: true
      deploy_explorer:
        type: boolean
        description: Deploy explorer (mainnet + testnet)
        default: true
      deploy_upload-code:
        type: boolean
        description: Deploy upload-code
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy_frontend:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      env: ${{ inputs.env }}
      app: vara-eth-idea
      component: frontend
      registry: ghcr.io/gear-tech/vara-eth-idea-frontend
      dockerfile: idea/vara-eth/frontend/Dockerfile
      context: .
      paths_filter: |
        idea/vara-eth/frontend/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_explorer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      env: ${{ inputs.env }}
      app: vara-eth-idea
      component: explorer-mainnet
      extra_components: |
        explorer-testnet
      registry: ghcr.io/gear-tech/vara-eth-idea-explorer
      dockerfile: idea/vara-eth/explorer/Dockerfile
      context: .
      paths_filter: |
        idea/vara-eth/explorer/**
        idea/vara-eth/indexer-db/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      env: ${{ inputs.env }}
      app: vara-eth-idea
      component: indexer-mainnet
      extra_components: |
        indexer-testnet
      init_containers: |
        migrations
      registry: ghcr.io/gear-tech/vara-eth-idea-indexer
      dockerfile: idea/vara-eth/indexer/Dockerfile
      context: .
      paths_filter: |
        idea/vara-eth/indexer/**
        idea/vara-eth/indexer-db/**
        apis/vara-eth/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_upload-code:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      env: ${{ inputs.env }}
      app: vara-eth-idea
      component: upload-code
      init_containers: |
        migrations
      registry: ghcr.io/gear-tech/vara-eth-idea-upload-code
      dockerfile: idea/vara-eth/upload-code-service/Dockerfile
      context: .
      paths_filter: |
        idea/vara-eth/upload-code-service/**
        apis/vara-eth/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}
