name: 'Release @gear-js/api'

on:
  push:
    branches: [main]
    paths:
      - apis/gear/package.json
  workflow_dispatch:

env:
  BINARYEN_VERSION: version_111

jobs:
  publish-to-npm:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check package version
        uses: EndBug/version-check@v1
        id: check
        with:
          file-name: apis/gear/package.json
          file-url: https://unpkg.com/@gear-js/api@latest/package.json
          static-checking: localIsNew

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: yarn install

      - name: Build @gear-js/api
        if: steps.check.outputs.changed == 'true'
        run: yarn build:gear-api

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        working-directory: apis/gear/lib
        run: |
          export token=$(printenv npm_token)
          npm config set //registry.npmjs.org/:_authToken=$token
          npm publish
        env:
          npm_token: ${{ secrets.NPM_TOKEN }}
